type Query {
  info: String
  getConversation(id1: Int!, id2: Int!): [Message!]
}

type Message {
  body: String
  sentby: Int
  receivedby: Int
  id: Int
}

type User {
  username: String!
  email: String!
}

type Mutation {
  createMessage(sentby: Int, receivedby: Int, body: String): Message
  createUser(email: String!, username: String): User
}
